#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : serpent
Version  : 1.28
Release  : 7
URL      : https://files.pythonhosted.org/packages/12/35/6b6e9bd34c7fd70065d9813f5401a645d9c8f2371dd941198ab9ae5630a1/serpent-1.28.tar.gz
Source0  : https://files.pythonhosted.org/packages/12/35/6b6e9bd34c7fd70065d9813f5401a645d9c8f2371dd941198ab9ae5630a1/serpent-1.28.tar.gz
Summary  : Serialization based on ast.literal_eval
Group    : Development/Tools
License  : MIT
Requires: serpent-license = %{version}-%{release}
Requires: serpent-python = %{version}-%{release}
Requires: serpent-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : pytz
BuildRequires : tox
BuildRequires : virtualenv

%description
Serpent serialization library (Python/.NET/Java)
================================================

%package license
Summary: license components for the serpent package.
Group: Default

%description license
license components for the serpent package.


%package python
Summary: python components for the serpent package.
Group: Default
Requires: serpent-python3 = %{version}-%{release}

%description python
python components for the serpent package.


%package python3
Summary: python3 components for the serpent package.
Group: Default
Requires: python3-core

%description python3
python3 components for the serpent package.


%prep
%setup -q -n serpent-1.28

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552241612
export LDFLAGS="${LDFLAGS} -fno-lto"
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/serpent
cp LICENSE %{buildroot}/usr/share/package-licenses/serpent/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/serpent/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
